# Generated by Django 3.2.12 on 2022-02-05 11:36

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, unique=True, verbose_name='نام در url')),
                ('title', models.TextField()),
                ('title_page', models.TextField()),
                ('description_page', models.TextField()),
                ('body', models.TextField()),
                ('txt_filter', models.TextField()),
                ('date', models.DateField(auto_now_add=True, verbose_name='تاریخ')),
                ('is_active', models.BooleanField(default=True)),
                ('cover', models.ImageField(blank=True, default='/Articles/MainImage', null=True, upload_to='Articles/MainImage')),
                ('alt_cover', models.CharField(max_length=100, null=True, verbose_name='alt تصویر')),
            ],
            managers=[
                ('articles', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ArticleComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=False, verbose_name='نمایش/عدم نمایش')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='article-image/')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='article-video/')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='app_article.article', verbose_name='مقاله')),
            ],
        ),
    ]
