# Generated by Django 3.2.12 on 2022-02-19 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_category', '0001_initial'),
        ('app_article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='articlecomments',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='app_article.article'),
        ),
        migrations.AddField(
            model_name='articlecomments',
            name='replay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_article.articlecomments', verbose_name='ریپلای'),
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app_category.category', verbose_name='دسته بندی'),
        ),
        migrations.AddField(
            model_name='article',
            name='next_article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='nextPost', to='app_article.article', verbose_name='پست بعذی'),
        ),
        migrations.AddField(
            model_name='article',
            name='prv_article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='prvPost', to='app_article.article', verbose_name='پست قبلی'),
        ),
        migrations.AddField(
            model_name='article',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='سازنده'),
        ),
    ]
