# Generated by Django 4.0.1 on 2022-01-28 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='user/image/default.png', null=True, upload_to='user/image'),
        ),
    ]
