# Generated by Django 4.0.1 on 2022-01-30 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='follower', to=settings.AUTH_USER_MODEL, verbose_name='دنبال شونده')),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='following', to=settings.AUTH_USER_MODEL, verbose_name='دنبال کننده')),
            ],
        ),
    ]
