# Generated by Django 3.2.12 on 2022-02-03 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enroll',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
