# Generated by Django 3.2.12 on 2022-02-11 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_order', '0002_enroll_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='enroll',
            name='token',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
