# Generated by Django 3.2.12 on 2022-02-21 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_order', '0002_enroll_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enroll',
            name='token',
        ),
    ]
