# Generated by Django 3.2.12 on 2022-02-01 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('number', models.CharField(max_length=14)),
                ('title', models.CharField(max_length=30)),
                ('message', models.TextField()),
                ('observed', models.BooleanField(default=False)),
            ],
        ),
    ]
