# Generated by Django 3.2.12 on 2022-03-04 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_course', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='episode',
            options={'ordering': ('number',)},
        ),
    ]
