# Generated by Django 4.0.1 on 2022-01-29 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_course', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='label',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
